config/routes.rb
RailsBootstrap::Application.routes.draw do
  root :to => "home#index"
  devise_for :users, :controllers => {:registrations => "registrations"}
  resources :users
  get "/submit/tables" => "home#submit", :as => "dashboard_submit"
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	# Index method for Dashboard data
	def index
		@tables = ActiveRecord::Base.connection.tables
	end

	# Submit form for index page to display graph
	def submit
		# debugger
		
		# table_name = params[:table]
		# render :index
	end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :update_sanitized_params, if: :devise_controller?

  def update_sanitized_params
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:name, :email, :password, :password_confirmation)}
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:name, :email, :password, :password_confirmation, :current_password)}
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.haml
%h3 Dashboard Home

/ display table collection in the dropdown
= select("Tables", "Table Name", @tables, { :include_blank => true })
= link_to 'Back', root_path
=# button_to 'Submit', dashboard_submit_path

%br


#container{style: "width:100%; height:400px;"}


:javascript
  $(function () { 
      $('#container').highcharts({
          chart: {
              type: 'bar'
          },
          title: {
              text: 'Fruit Consumption'
          },
          xAxis: {
              categories: ["Apples", 'Bananas', 'Oranges', 'Grapes', 'Lemons']
          },
          yAxis: {
              title: {
                  text: 'Fruit eaten'
              }
          },
          series: [{
              name: 'Jane',
              data: [1, 3, 8, 12, 19]
          }, {
              name: 'John',
              data: [5, 7, 3, 15, 10]
          }]
      });
  });

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>
  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
<% else %>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Users', users_path %></li>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Dashboard'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Dashboard'}"}
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/users/index.html.haml
%h3 Users
%ul.users
  - @users.each do |user|
    %li
      = link_to user.name, user
      signed up #{user.created_at.to_date}

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}
= link_to 'Edit account', edit_user_path